import { execSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(__dirname, "..");
const inputFile = path.resolve(rootDir, "src/tailwind.css");
const tempCssFile = path.resolve(rootDir, "src/.temp.tailwind.css");
const generatedDir = path.resolve(rootDir, "src/generated");
const outputFile = path.resolve(generatedDir, "tailwind.styles.ts");

export function buildStyles() {
  if (!fs.existsSync(generatedDir)) {
    fs.mkdirSync(generatedDir, { recursive: true });
  }

  execSync(`npx @tailwindcss/cli -i "${inputFile}" -o "${tempCssFile}" --minify`, {
    cwd: rootDir,
    stdio: "inherit",
  });

  const cssContent = fs.readFileSync(tempCssFile, "utf-8");

  if (fs.existsSync(tempCssFile)) {
    fs.unlinkSync(tempCssFile);
  }

  const escapedCss = cssContent.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");

  const tsContent = `// Auto-generated by build-styles.mjs - DO NOT EDIT MANUALLY
import { css } from "lit";

export const tailwindStyles = css\`
${escapedCss}
\`;
`;

  fs.writeFileSync(outputFile, tsContent, "utf-8");
  console.log(`[widget] Successfully generated ${outputFile}`);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  buildStyles();
}
